// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFU8I63nMXYhsx0ij-GQpVUI24kKi7AJU',
    appId: '1:288558159532:web:3111b08b8dcdc93937f109',
    messagingSenderId: '288558159532',
    projectId: 'sandwhich-shop',
    authDomain: 'sandwhich-shop.firebaseapp.com',
    storageBucket: 'sandwhich-shop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeXfpkA7MkSltL8atAbdCuoJswYZtQqFA',
    appId: '1:288558159532:android:39334d7e7254436337f109',
    messagingSenderId: '288558159532',
    projectId: 'sandwhich-shop',
    storageBucket: 'sandwhich-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4sqRVURwSQfSiF2ocD0EjbfwGjzSNpMI',
    appId: '1:288558159532:ios:91a3608b4e9b6c2537f109',
    messagingSenderId: '288558159532',
    projectId: 'sandwhich-shop',
    storageBucket: 'sandwhich-shop.firebasestorage.app',
    iosBundleId: 'com.example.sandwichShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4sqRVURwSQfSiF2ocD0EjbfwGjzSNpMI',
    appId: '1:288558159532:ios:91a3608b4e9b6c2537f109',
    messagingSenderId: '288558159532',
    projectId: 'sandwhich-shop',
    storageBucket: 'sandwhich-shop.firebasestorage.app',
    iosBundleId: 'com.example.sandwichShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFU8I63nMXYhsx0ij-GQpVUI24kKi7AJU',
    appId: '1:288558159532:web:0f67ec10f1a5ff7c37f109',
    messagingSenderId: '288558159532',
    projectId: 'sandwhich-shop',
    authDomain: 'sandwhich-shop.firebaseapp.com',
    storageBucket: 'sandwhich-shop.firebasestorage.app',
  );
}
